name: CI
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    name: ESLint & TSC
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Linters
        uses: ./.github/actions
        with:
          command: yarn lint
  test:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tests
        uses: ./.github/actions
        with:
          command: yarn test
